name: Test

on: [push, pull_request]

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.2
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
      - name: Install
        run: |
          npx lerna bootstrap --hoist
      - name: Lint
        run: |
          npm run pretest
          npm run lint

  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.2
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
      - name: Install
        run: |
          npx lerna bootstrap --hoist
      - name: Jest
        run: |
          npm test

  Schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.2
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
      - name: Install
        run: |
          npx lerna bootstrap --hoist
      - name: Prisma Validation
        run: |
          npx prisma generate
